CREATE TABLE SISTEMADEAVALIACAO.LINGUAGEM (
  ID_LINGUAGEM SERIAL NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID_LINGUAGEM)
);

CREATE TABLE SISTEMADEAVALIACAO.CANDIDATO (
  ID_CANDIDATO SERIAL NOT NULL,
  REDE_SOCIAL VARCHAR(100) NULL,
  TELEFONE INTEGER  NULL,
  NOME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PRIMARY KEY(ID_CANDIDATO)
);

CREATE TABLE SISTEMADEAVALIACAO.FUNCIONARIO (
  ID_FUNCIONARIO SERIAL NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  SENHA BYTEA NOT NULL,
  ADMINISTRADOR BOOL NOT NULL DEFAULT FALSE,
  AVALIADOR BOOL NOT NULL DEFAULT FALSE,
  ESPECIALIDADE VARCHAR(50) NULL,
  VISIVEL BOOL NOT NULL DEFAULT TRUE,
  PRIMARY KEY(ID_FUNCIONARIO)
);

CREATE TABLE SISTEMADEAVALIACAO.CRITERIO (
  ID_CRITERIO SERIAL NOT NULL,
  LINGUAGEM_ID_LINGUAGEM INTEGER  NOT NULL,
  DESCRICAO VARCHAR(100) NOT NULL,
  OBRIGATORIO BOOL NOT NULL DEFAULT TRUE,
  PRIMARY KEY(ID_CRITERIO),
  FOREIGN KEY(LINGUAGEM_ID_LINGUAGEM)
    REFERENCES SISTEMADEAVALIACAO.LINGUAGEM(ID_LINGUAGEM)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SISTEMADEAVALIACAO.PROVA (
  ID_PROVA SERIAL NOT NULL,
  CANDIDATO_ID_CANDIDATO INTEGER  NOT NULL,
  LINGUAGEM_ID_LINGUAGEM INTEGER  NOT NULL,
  LINK_PROVA VARCHAR(50) NOT NULL,
  PRAZO INTEGER NOT NULL,
  DATA_SOLIC_AVA DATE NOT NULL,
  PRIMARY KEY(ID_PROVA),
  FOREIGN KEY(LINGUAGEM_ID_LINGUAGEM)
    REFERENCES SISTEMADEAVALIACAO.LINGUAGEM(ID_LINGUAGEM)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CANDIDATO_ID_CANDIDATO)
    REFERENCES SISTEMADEAVALIACAO.CANDIDATO(ID_CANDIDATO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SISTEMADEAVALIACAO.AVALIACAO (
  ID_AVALIACAO SERIAL NOT NULL ,
  FUNCIONARIO_ID_FUNCIONARIO INTEGER  NOT NULL,
  PROVA_ID_PROVA INTEGER  NOT NULL,
  PONTOS_FORTES VARCHAR NOT NULL,
  PONTOS_MELHORAR VARCHAR NOT NULL,
  PARECER VARCHAR NOT NULL,
  DATA_CONC_AVA DATE NOT NULL,
  DATA_INICIO_AVA DATE NOT NULL,
  STATUS_AVA VARCHAR NULL,
  PRIMARY KEY(ID_AVALIACAO),
  FOREIGN KEY(FUNCIONARIO_ID_FUNCIONARIO)
    REFERENCES SISTEMADEAVALIACAO.FUNCIONARIO(ID_FUNCIONARIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PROVA_ID_PROVA)
    REFERENCES SISTEMADEAVALIACAO.PROVA(ID_PROVA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);
 
CREATE TABLE SISTEMADEAVALIACAO.CRITERIO_has_ARMAZENA_CRITERIOS (
  ID SERIAL NOT NULL,
  CRITERIO_ID_CRITERIO INTEGER  NOT NULL,
  AVALIACAO_ID_AVALIACAO INTEGER NOT NULL,
  RESPONDIDO BOOL NOT NULL DEFAULT FALSE,
  PRIMARY KEY(ID),
  FOREIGN KEY(AVALIACAO_ID_AVALIACAO)
    REFERENCES SISTEMADEAVALIACAO.AVALIACAO(ID_AVALIACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CRITERIO_ID_CRITERIO)
    REFERENCES SISTEMADEAVALIACAO.CRITERIO(ID_CRITERIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE SISTEMADEAVALIACAO.CRITERIO_has_AVALIACAO (
  CRITERIO_ID_CRITERIO INTEGER  NOT NULL,
  AVALIACAO_ID_AVALIACAO INTEGER NOT NULL,
  PRIMARY KEY(CRITERIO_ID_CRITERIO, AVALIACAO_ID_AVALIACAO),
  FOREIGN KEY(CRITERIO_ID_CRITERIO)
    REFERENCES SISTEMADEAVALIACAO.CRITERIO(ID_CRITERIO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(AVALIACAO_ID_AVALIACAO)
    REFERENCES SISTEMADEAVALIACAO.AVALIACAO(ID_AVALIACAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

